let firstnameDOM = document.getElementById("firstname");
console.log(firstnameDOM);
console.log(firstnameDOM.value);
let inputsDom = document.getElementsByClassName("input");
console.log(inputsDom);
let firstnameq1 = document.querySelector("#firstname");
let firstnameq2 = document.querySelector(".input");
let firstnameq3 = document.querySelector("input[name=firstname]");
let firstnameq4 = document.querySelectorAll(".input");
console.log(firstnameq1);
console.log(firstnameq2);
console.log(firstnameq3);
console.log(firstnameq4);
